### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by stevepowell99** [rickstaa/todoist-global-shortcuts-WIN10#2]
Thanks, I don't need this now, how can I uninstall?

**Comment by rickstaa** [comment]
Dear Steve,

No problem. I just programmed an uninstaller for the workaround. You can get it by downloading the new version.

May I ask why you don't need the work around anymore?

Is it not working like expected or do you want me to add some changes?

Tip: I changed the shortcut keys to a and s because they are more convenient to me this can be easily done. I can create a menu where you can input your own short keys as well if you like.

Thanks in advance,
Greetings,
Rick,

**Comment by stevepowell99** [comment]
thanks, not using todoist any more.

**Comment by rickstaa** [comment]
Thanks for the feedback!
